services:
  web:
    build:
      context: manifest/images/
      dockerfile: php82/Dockerfile
    image: docker.io/ccarney16/caddyserver:php-8.2
    ports:
    - 8080:8080
    read_only: true
    volumes:
    - caddyhome:/var/lib/caddy
    - tmpfs:/tmp
  cron:
    command: cron
    image: docker.io/ccarney16/caddyserver:php-8.2
    read_only: true
    restart: always
    volumes:
    - ./conf.d/yacron.d/:/etc/yacron.d
    volumes_from:
    - web
  # worker:
  #   command: whatever you need running persistently
  #   image: docker.io/ccarney16/caddyserver:php-8.2
  #   read_only: true
  #   restart: always
  #   volumes_from:
  #   - web
volumes:
  caddyhome:
  tmpfs: